name: "Check new/changed code coverage"

inputs:
    fail-under:
        description: "Target coverage percentage (0-100)"
        type: number
        default: 80
    coverage-path:
        description: "Path to coverage reports (uses common defaults if not specified)"
        type: string
        default: "coverage/clover.xml"
    compare-branch:
        description: "Branch to compare coverage against"
        type: string
        default: ${{ github.event.pull_request.base.ref }}
    exclude:
        description: "Exclude files from coverage check (whitespace-separated list)"
        type: string
        default: ""

runs:
    using: "composite"
    steps:
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.x"

        - name: Install diff-cover
          shell: bash
          run: pip install diff-cover

        - name: Fetch base branch for comparison
          shell: bash
          run: |
              git fetch origin ${{ github.event.pull_request.base.ref }}
              git checkout ${{ github.event.pull_request.head.sha }}

        - name: Check coverage
          shell: bash
          run: |
              diff-cover ${{ inputs.coverage-path }} --compare-branch=origin/${{ inputs.compare-branch }} --fail-under=${{ inputs.fail-under }} --exclude ${{ inputs.exclude }}
